### ISSUE TITLE
error after join voice chat

### ISSUE THREAD

**Issue by Jroddmqz** [callsmusic/tgvc-userbot#14]
After joining the vc this appears on the console. Commands like !ping, !uptime keep working but don't play music.

>>> USERBOT STARTED
Task exception was never retrieved
future: <Task finished name='Task-110' coro=<network_status_changed_handler() done, defined at /home/ubuntu/tgvc-userbot/utils/vc.py:123> exception=ValueError('Peer id invalid: -100525701833')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/storage/sqlite_storage.py", line 147, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -100525701833'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/tgvc-userbot/utils/vc.py", line 127, in network_status_changed_handler
    await mp.send_text(f"{emoji.CHECK_MARK_BUTTON} joined the voice chat")
  File "/home/ubuntu/tgvc-userbot/utils/vc.py", line 92, in send_text
    message = await client.send_message(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_message.py", line 127, in send_message
    peer=await self.resolve_peer(chat_id),
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 87, in resolve_peer
    peer_type = utils.get_peer_type(peer_id)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/utils.py", line 203, in get_peer_type
    raise ValueError(f"Peer id invalid: {peer_id}")
ValueError: Peer id invalid: -100525701833

**Comment by dashezup** [comment]
It failed to send the message about it joined the voice chat to the voice chat group.
