### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by LovelyHaochi** [callsmusic/tgvc-userbot#19]
When I executed `!join`, he got the following error:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/tgvc-userbot/plugins/vc/player.py", line 297, in join_group_call
    group_call.client = client
AttributeError: can't set attribute
```

This is my logs:
```
root@ip-172-31-40-61:~/tgvc-userbot# python3 userbot.py 
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

tgcalls v1.0.0, Copyright (C) 2020-2021 Il`ya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3) 


>>> USERBOT STARTED
can't set attribute
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/tgvc-userbot/plugins/vc/player.py", line 296, in join_group_call
    group_call.client = client
AttributeError: can't set attribute
```

**Comment by dashezup** [comment]
it's a bug that it does not works with latest release of pytgcalls (v1.0.0), I just confirmed it. the current workaround is installing the previous version of pytgcalls

```console
user@hostname ~ $ pip uninstall pytgcalls
user@hostname ~ $ pip install pytgcalls==0.0.23
```
