### ISSUE TITLE
Not run when i send !join

### ISSUE THREAD

**Issue by mengxin239** [callsmusic/tgvc-userbot#25]
when i send !join ,it only will quit voice chat a few seconds after joining
and will print this on console
`'GroupCall' object has no attribute 'params'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 63, in _process_update
    await self._update_to_handler[type(update)](update)
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 75, in _process_group_call_update
    call = GroupCallWrapper(update.call.id, update.call.params)
AttributeError: 'GroupCall' object has no attribute 'params'
`

**Comment by dashezup** [comment]
I haven't check this project for a long time and don't feel much motivation to check this for now.

it looks like a pytgcalls update break some codes, you may try some old version of pytgcalls

**Comment by mengxin239** [comment]
when i install pyrogram1.2.5,it work on my server.
